### PR TITLE
Laravel 9.x Shift

### PR DESCRIPTION
**Pull request by andreapollastri**
This pull request includes the changes for upgrading to Laravel 9.x. Feel free to commit any additional changes to the `shift-84797` branch.

**Before merging**, you need to:

- Checkout the `shift-84797` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by andreapollastri** [comment]
:information_source: Laravel 9 moved the `resources/lang` folder to the top level of the project. While Shift moved and replaced references to this folder, you may have additional references to this folder which need to be updated.

**Comment by andreapollastri** [comment]
:warning: Laravel 9 upgraded to Flysystem 3.0 causing the behavior of the `Storage` facade to change slightly:

* Write operations (such as `put` and `write`) now overwrite existing files by default and return `false` instead of throwing an exception.
* Read operations (such as `get` and `download`) now return `null` instead of a `FileNotFoundException` when a file is missing.
* The `delete` operation now returns `true` even if the file did not exist.

For more details, you may review the [Flysystem 3.x](https://laravel.com/docs/9.x/upgrade#flysystem-3) section of the _Upgrade Guide_.

**Comment by andreapollastri** [comment]
:warning: Laravel 9 transitioned from SwiftMailer to Symfony Mailer. While this transition should be relatively seamless and Shift automates any tedious changes, some changes may not reliably be automated.

**Dependencies**
Some mail providers may require an additional dependency. For example, if you are using Mailgun, then you will need to install the `symfony/mailgun-mailer` package:

```sh
composer require symfony/mailgun-mailer symfony/http-client
```

For more details on what has changed you may review the [Symfony Mailer](https://laravel.com/docs/9.x/upgrade#symfony-mailer) section of the _Upgrade Guide_.

**Comment by andreapollastri** [comment]
:warning: The `public/web.config` file has been removed from new Laravel projects. The presence of this file creates a potential security risk for projects not using Microsoft IIS as their web server.

Shift detected this file was modified and did not remove it. Unless you are using Microsoft IIS as your web server, you should remove this file.

**Comment by andreapollastri** [comment]
:warning: The `FILESYSTEM_DRIVER` environment variable was renamed to `FILESYSTEM_DISK` in Laravel 9. Shift did not find this variable referenced in your committed files, but you should review any additional environment configuration and rename this variable.

**Comment by andreapollastri** [comment]
:information_source: The `FILESYSTEM_CLOUD` environment variable was removed in a later release of Laravel 8. While you may still use the `cloud` disk, you are encouraged to [configure your own disks](https://laravel.com/docs/9.x/filesystem#configuration).

**Comment by andreapollastri** [comment]
:warning: The `token` driver for API authentication is no longer available. This driver was not very robust and was removed from the documentation. Laravel now recommends using [Sanctum](https://laravel.com/docs/9.x/sanctum).

If you were using the `token` driver, you may re-add it within your `auth.php` configuration file then migrate to _Sanctum_ at your convenience.

**Comment by andreapollastri** [comment]
:information_source: Shift [updated your dependencies](https://github.com/andreapollastri/cipi/pull/464/commits/c24953c8b6d512a3a1afac909f3a2b10f010ce8a?w=1) for Laravel 9. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 9. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

The following dependencies were updated by a major version and may have their own changes. You may check their changelog for any additional upgrade steps.

- [ ] [barryvdh/laravel-dompdf](https://packagist.org/packages/barryvdh/laravel-dompdf)

**Comment by andreapollastri** [comment]
:information_source: Laravel 9 adopted [anonymous migrations](https://laravel-news.com/laravel-anonymous-migrations). Shift [automated this change](https://github.com/andreapollastri/cipi/pull/464/commits/bdb15f391f1676cd6ebc77fbd5221d5f38e8453e?w=1) to align with modern Laravel conventions and avoid naming migrations.

**Comment by andreapollastri** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 6. If you are directly interacting with any Symfony component, you should review the [Symfony change log](https://github.com/symfony/symfony/blob/6.0/UPGRADE-6.0.md) for additional changes.

**Comment by andreapollastri** [comment]
:information_source: The HTTP client has been updated to have a default timeout of 30 seconds. Previously there was no default. The underlying request would wait indefinitely. Now an exception is thrown after 30 seconds.

If you find your requests need longer, you may prefix your request to specify a timeout:

```php
Http::timeout(60)->get("https://laravelshift.com");
```

**Comment by rekliner** [comment]
looks like your existing composer.lock remained unchanged.  You should regenerate to see if tests pass.

**Pull request closed without merging**
